BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Models/DTO/PhuongThucThanhToan.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FreshFoodMongo.Models.DTO
{
    public class PhuongThucThanhToan
    {
        [BsonId]
        public ObjectId _id { get; set; }
        [BsonElement]
        public Guid IDPhuongThucThanhToan { get; set; }
        [BsonElement]
        public string TenPhuongThucThanhToan { get; set; }
        [BsonElement]
        public DateTime? CreatedDate { get; set; }
        [BsonElement]
        public string CreatedBy { get; set; }
        [BsonElement]
        public DateTime? ModifiedDate { get; set; }
        [BsonElement]
        public string ModifiedBy { get; set; }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Controllers/PhuongThucThanhToanController.cs
using FreshFoodMongo.Models.DAO.Admin;
using FreshFoodMongo.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreshFoodMongo.Areas.Admin.Controllers
{
    public class PhuongThucThanhToanController : BaseController
    {
        PhuongThucThanhToanDAO ptttDao = new PhuongThucThanhToanDAO();

        // GET: Admin/PhuongThucThanhToan
        public ActionResult Index(int? page, int? PageSize, string searching = "")
        {
            ViewBag.SearchString = searching;
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="10", Text= "10" },
                new SelectListItem() { Value="15", Text= "15" },
                new SelectListItem() { Value="20", Text= "20" },
                new SelectListItem() { Value="25", Text= "25" },
                new SelectListItem() { Value="50", Text= "50" }
            };
            int pageNumber = (page ?? 1);
            int pagesize = (PageSize ?? 10);
            ViewBag.psize = pagesize;
            ViewBag.Count = ptttDao.ListSimple(searching).Count();
            return View(ptttDao.ListSimpleSearch(pageNumber, pagesize, searching));
        }

        public ActionResult Details(Guid id)
        {
            PhuongThucThanhToan phuongthucthanhtoan = ptttDao.GetByID(id);
            return View(phuongthucthanhtoan);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string ten)
        {
            PhuongThucThanhToan phuongthucthanhtoan = new PhuongThucThanhToan();
            phuongthucthanhtoan.IDPhuongThucThanhToan = Guid.NewGuid();
            phuongthucthanhtoan.TenPhuongThucThanhToan = ten;
            if (ModelState.IsValid)
            {
                ptttDao.Add(phuongthucthanhtoan);
                return RedirectToAction("Index");
            }
            else
            {
                return View(phuongthucthanhtoan);
            }
        }

        public ActionResult Edit(Guid id)
        {
            return View(ptttDao.GetByID(id));
        }

        [HttpPost]
        public ActionResult Edit(Guid id, string ten)
        {
            PhuongThucThanhToan phuongthucthanhtoan = ptttDao.GetByID(id);
            phuongthucthanhtoan.TenPhuongThucThanhToan = ten;
            if (ModelState.IsValid)
            {
                ptttDao.Edit(phuongthucthanhtoan);
                return RedirectToAction("Index");
            }
            else
            {
                return View(phuongthucthanhtoan);
            }
        }

        public ActionResult Delete(Guid id)
        {
            ptttDao.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/PhuongThucThanhToan/Create.cshtml
@model FreshFoodMongo.Models.DTO.PhuongThucThanhToan

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Phương thức thanh toán - Thêm mới
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Phương thức thanh toán</label>
                <input type="text" class="form-control" name="ten" placeholder="Nhập tên" value=" @Html.DisplayFor(model => model.TenPhuongThucThanhToan)" required>
            </div>
        </div>
        <br />

        <button type="submit" class="btn btn-primary" style="width:110px">
            <a class="fa fa-save"></a> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <a class="fa fa-th-list"></a> &nbsp;
            @Html.ActionLink("Danh sách", "Index")
        </button>
    </div>
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/PhuongThucThanhToan/Details.cshtml
@model FreshFoodMongo.Models.DTO.PhuongThucThanhToan

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Loại thanh toán - Thông tin thanh toán(#@Model.TenPhuongThucThanhToan)
}

<div>
    <dl class="dl-horizontal">
        <dt>
            Tên phương thức thanh toán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenPhuongThucThanhToan)
        </dd>
    </dl>
</div>

<button type="button" class="btn btn-primary">
    <a class="fa fa-edit"></a> &nbsp;
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.IDPhuongThucThanhToan })
</button>
<button type="button" class="btn btn-warning">
    <a class="fa fa-th-list"></a> &nbsp;
    @Html.ActionLink("Danh sách", "Index")
</button>

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/PhuongThucThanhToan/Edit.cshtml
@model FreshFoodMongo.Models.DTO.PhuongThucThanhToan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Loại phương thức thanh toán - Chỉnh sửa (@Model.TenPhuongThucThanhToan)
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDPhuongThucThanhToan)

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Tên phương thức thanh toán</label>
                <input type="text" class="form-control" name="ten" placeholder="Nhập tên phương thức thanh toán ..." value=" @Html.DisplayFor(model => model.TenPhuongThucThanhToan)" required>
            </div>
        </div>
        <br />


        <button type="submit" class="btn btn-primary" style="width:110px">
            <a class="fa fa-save"></a> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <a class="fa fa-th-list"></a> &nbsp;
            @Html.ActionLink("Danh sách", "Index")
        </button>
    </div>
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/PhuongThucThanhToan/Index.cshtml
@model PagedList.IPagedList<FreshFoodMongo.Models.DTO.PhuongThucThanhToan>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int i;
    if (Model.Count == ViewBag.psize)
    {
        i = Model.PageNumber * Model.Count - Model.Count;
    }
    else
    {
        i = ViewBag.Count - Model.Count;
    }

    string GetSTT()
    {
        i++;
        return Convert.ToString(i);
    }
}

@section header
{
    Danh sách Phương thức thanh toán
}

<table style="width:100%; margin-bottom:10px">
    <tr>
        <td>
            @using (Html.BeginForm("Index", "PhuongThucThanhToan", FormMethod.Get, new { id = "form1" }))
            {
                <p style="float:left; color:navy; height:32px"><b>Hiển thị &nbsp; </b>@Html.DropDownList("pageSize") &nbsp; <b>bản ghi / trang </b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

                <input type="text" name="searching" value="@ViewBag.SearchString" placeholder="Nhập thông tin tìm kiếm ..." style="width: 400px;" />
                <input type="submit" value="Tìm kiếm" />
            }
        </td>
        <td>
            <button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                <i class="fa fa-plus-square"></i> &nbsp;
                @Html.ActionLink("Thêm mới", "Create", "PhuongThucThanhToan")
            </button>
        </td>
    </tr>
</table>

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>STT</th>
            <th>Tên phương thức thanh toán</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(GetSTT())
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenPhuongThucThanhToan)
                </td>
                <td>
                    <i class="fa fa-edit"></i> &nbsp;
                    @Html.ActionLink("Sửa", "Edit", new { id = item.IDPhuongThucThanhToan }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-trash"></i> &nbsp;
                    @Html.ActionLink("Xóa", "Delete", new { id = item.IDPhuongThucThanhToan }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
                </td>

            </tr>
        }
    </tbody>
</table>


@using (Html.BeginForm("Index", "PhuongThucThanhToan", FormMethod.Get, new { id = "form1" }))
{
    <div class="pager">
        <table style="width:100%">
            <col style="width:50%">
            <col style="width:50%">
            <tr>
                <td style="float:left">
                    <b style="color:navy">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount &nbsp;&nbsp;-&nbsp;&nbsp;
                        @if (Model.Count == ViewBag.psize)
                        {
                            <span>Đang hiển thị (@(((Model.PageNumber * Model.Count) - Model.Count) + 1)-@(Model.PageNumber * Model.Count)) / @ViewBag.Count</span>
                        }
                        else
                        {
                            <span>Đang hiển thị (@((ViewBag.Count - Model.Count) + 1)-@(ViewBag.Count)) / @ViewBag.Count</span>
                        }
                    </b>
                </td>
                <td style="float:right; margin-top:-20px">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = ViewBag.psize, @searching = @ViewBag.SearchString }))
                </td>
            </tr>
        </table>
    </div>
}
<script src="~/Assets/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $("#checkAll").click(function () {
            if (this.checked) {
                $(".chkbox").prop('checked', $(this).prop('checked', true));
            }
            else {
                $('.chkbox').each(function () { this.checked = false; });
            }
        });
        $('.chkbox').on('click', function () {
            if ($('.chkbox:checked').length == $('.chkbox').length) {
                $('#checkAll').prop('checked', true);
            } else {
                $('#checkAll').prop('checked', false);
            }
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $("#pageSize").change(function () {
            $("#form1").submit();
        });
    });
</script>