BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Models/DTO/HoaDonNhap.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FreshFoodMongo.Models.DTO
{
    public class HoaDonNhap
    {
        [BsonId]
        public ObjectId _id { get; set; }
        [BsonElement]
        public Guid IDHoaDonNhap { get; set; }
        [BsonElement]
        public Guid IDNhaCungCap { get; set; }
        [BsonElement]
        public int MaSo { get; set; }
        [BsonElement]
        public string GhiChu { get; set; }
        [BsonElement]
        public decimal? TienHang { get; set; }
        [BsonElement]
        public decimal? TienShip { get; set; }
        [BsonElement]
        public decimal TienGiam { get; set; }
        [BsonElement]
        public decimal? TongTien { get; set; }
        [BsonElement]
        public DateTime? CreatedDate { get; set; }
        [BsonElement]
        public string CreatedBy { get; set; }
        [BsonElement]
        public DateTime? ModifiedDate { get; set; }
        [BsonElement]
        public string ModifiedBy { get; set; }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Controllers/HoaDonNhapController.cs
using FreshFoodMongo.Models.DAO;
using FreshFoodMongo.Models.DAO.Admin;
using FreshFoodMongo.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreshFoodMongo.Areas.Admin.Controllers
{
    public class HoaDonNhapController : Controller
    {
        BaseDAO baseDao = new BaseDAO();
        HoaDonNhapDAO hdnDao = new HoaDonNhapDAO();
        ChiTietHoaDonNhapDAO cthdnDao = new ChiTietHoaDonNhapDAO();

        // GET: Admin/HoaDonNhap
        public ActionResult Index(int? page, int? PageSize, string searching = "")
        {
            ViewBag.SearchString = searching;
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="10", Text= "10" },
                new SelectListItem() { Value="15", Text= "15" },
                new SelectListItem() { Value="20", Text= "20" },
                new SelectListItem() { Value="25", Text= "25" },
                new SelectListItem() { Value="50", Text= "50" }
            };
            int pageNumber = (page ?? 1);
            int pagesize = (PageSize ?? 10);
            ViewBag.psize = pagesize;
            ViewBag.Count = hdnDao.ListSimple(searching).Count();
            return View(hdnDao.ListSimpleSearch(pageNumber, pagesize, searching));
        }

        public ActionResult Details(Guid id)
        {
            HoaDonNhap hoadonnhap = hdnDao.GetByID(id);
            return View(hoadonnhap);
        }

        public ActionResult Create()
        {
            ViewBag.ListNhaCungCap = new SelectList(baseDao.getDataNhaCungCap(), "IDNhaCungCap", "Ten", "IDNhaCungCap");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Guid idnhacungcap, string ghichu)
        {
            HoaDonNhap hoadonnhap = new HoaDonNhap();
            hoadonnhap.IDHoaDonNhap = Guid.NewGuid();
            hoadonnhap.IDNhaCungCap = idnhacungcap;
            hoadonnhap.GhiChu = ghichu;
            hoadonnhap.TienHang = 0;
            hoadonnhap.TienShip = 0;
            hoadonnhap.TienGiam = 0;
            hoadonnhap.TongTien = 0;

            hoadonnhap.CreatedDate = DateTime.Now;
            hoadonnhap.CreatedBy = (string)Session["USERNAME_SESSION"];
            hoadonnhap.ModifiedDate = DateTime.Now;
            hoadonnhap.ModifiedBy = (string)Session["USERNAME_SESSION"];

            if (ModelState.IsValid)
            {
                hdnDao.Add(hoadonnhap);
                return RedirectToAction("Index");
            }
            else
            {
                return View(hoadonnhap);
            }
        }

        public ActionResult Edit(Guid id)
        {
            return View(hdnDao.GetByID(id));
        }

        [HttpPost]
        public ActionResult Edit(Guid id, string ghichu)
        {
            HoaDonNhap hoadonnhap = hdnDao.GetByID(id);
            hoadonnhap.GhiChu = ghichu;

            hoadonnhap.ModifiedDate = DateTime.Now;
            hoadonnhap.ModifiedBy = (string)Session["USERNAME_SESSION"];

            if (ModelState.IsValid)
            {
                hdnDao.Edit(hoadonnhap);
                return RedirectToAction("Index");
            }
            return View(hoadonnhap);
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                hdnDao.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("ErrorConstraint");
            }
        }

        public ActionResult IndexChiTietHoaDonNhap(Guid idhdn, Guid idncc)
        {
            var listChiTietHoaDonNhap = cthdnDao.GetListChiTietHDNByIDHDN(idhdn);

            if (listChiTietHoaDonNhap == null)
                return HttpNotFound();

            ViewBag.IDHoaDonNhap = idhdn;
            ViewBag.IDNhaCungCap = idncc;

            return PartialView(listChiTietHoaDonNhap);
        }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/HoaDonNhap/Create.cshtml
@model FreshFoodMongo.Models.DTO.HoaDonNhap

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section header
{
    Hóa đơn nhập - Thêm hóa đơn nhập
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Nhà cung cấp</label><br />
                @Html.DropDownList("IDNhaCungCap", (IEnumerable<SelectListItem>)ViewBag.ListNhaCungCap, "  --  Nhà cung cấp  --  ", new { @class = "combobox", @style = "height:32px; width:332px; required" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Ghi chú</label><br />
                <input type="text" class="form-control" name="ghichu" placeholder="Nhập ghi chú ..." value=" @Html.DisplayFor(model => model.GhiChu)">
            </div>
        </div>
        <br />

        <button type="submit" class="btn btn-primary" value="Create" style="width:110px">
            <i class="fa fa-save"></i> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <i class="fa fa-arrow-left"></i> &nbsp;
            @Html.ActionLink("Trở về", "Index")
        </button>
    </div>
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/HoaDonNhap/Details.cshtml
@model FreshFoodMongo.Models.DTO.HoaDonNhap

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
}

@section header
{
    Hóa đơn nhập - Thông tin hóa đơn nhập (#@Model.MaSo.ToString("D6"))
}
<div>
    <table>
        <tr>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        Mã hóa đơn nhập:
                    </dt>

                    <dd>
                        @Html.Raw(Model.MaSo.ToString("D6"))
                    </dd>
                    <dt>
                        Nhà cung cấp:
                    </dt>

                    <dd>
                        @Html.Raw(commonDao.getRf_TenNhaCungCap(Model.IDNhaCungCap))
                    </dd>
                    <dt>
                        Ngày tạo:
                    </dt>

                    <dd>
                        @Html.Raw(@Convert.ToDateTime(Model.CreatedDate).ToString("dd/MM/yyyy"))
                    </dd>

                    <dt>
                        Ghi chú:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GhiChu)
                    </dd>
                    <dt>
                        Tiền hàng:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TienHang) VNĐ
                    </dd>

                    <dt>
                        Tiền ship:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TienShip) VNĐ
                    </dd>

                    <dt>
                        Tiền giảm:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TienGiam) VNĐ
                    </dd>

                    <dt>
                        Tổng tiền:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TongTien) VNĐ
                    </dd>
                </dl>
            </td>
        </tr>
    </table>
    <br />
    <button type="button" class="btn btn-primary" style="width:110px">
        <a class="fa fa-edit"></a> &nbsp;
        @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.IDHoaDonNhap })
    </button>
    <button type="button" class="btn btn-warning" style="width:110px">
        <a class="fa fa-arrow-left"></a> &nbsp;
        @Html.ActionLink("Trở về", "Index")
    </button>
    <br /><br />
    <hr />
    <h4>
        <i class="fa fa-list-ol"></i>
        <b style="color:darkgreen">&nbsp;Chi tiết hóa đơn nhập</b>
    </h4>
    @Html.Action("IndexChiTietHoaDonNhap", new { idhdn = Model.IDHoaDonNhap, idncc = Model.IDNhaCungCap })
</div>
<br />

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/HoaDonNhap/Edit.cshtml
@model FreshFoodMongo.Models.DTO.HoaDonNhap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
}


@section header
{
    Hóa đơn nhập - Sửa hóa đơn nhập (#@Model.MaSo.ToString("D6"))
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDHoaDonNhap)

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Nhà cung cấp</label><br />
                <input type="text" class="form-control" value=" @Html.Raw(commonDao.getRf_TenNhaCungCap(Model.IDNhaCungCap))" readonly>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Ghi chú</label><br />
                <input type="text" class="form-control" name="ghichu" placeholder="Nhập ghi chú ..." value=" @Html.DisplayFor(model => model.GhiChu)">
            </div>
        </div>

        <button type="submit" class="btn btn-primary" value="Create" style="width:110px">
            <i class="fa fa-save"></i> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <i class="fa fa-arrow-left"></i> &nbsp;
            @Html.ActionLink("Trở về", "Index")
        </button>
    </div>
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/HoaDonNhap/Index.cshtml
@model PagedList.IPagedList<FreshFoodMongo.Models.DTO.HoaDonNhap>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int i;
    if (Model.Count == ViewBag.psize)
    {
        i = Model.PageNumber * Model.Count - Model.Count;
    }
    else
    {
        i = ViewBag.Count - Model.Count;
    }

    string GetSTT()
    {
        i++;
        return Convert.ToString(i);
    }

    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
}

@section header
{
    Danh sách Hóa đơn nhập
}

<table style="width:100%; margin-bottom:10px">
    <tr>
        <td>
            @using (Html.BeginForm("Index", "HoaDonNhap", FormMethod.Get, new { id = "form1" }))
            {
                <p style="float:left; color:navy; height:32px"><b>Hiển thị &nbsp; </b>@Html.DropDownList("pageSize") &nbsp; <b>bản ghi / trang </b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

                <input type="text" name="searching" value="@ViewBag.SearchString" placeholder="Nhập thông tin tìm kiếm ..." style="width: 400px;" />
                <input type="submit" value="Tìm kiếm" />
            }
        </td>
        <td>
            <button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                <i class="fa fa-plus-square"></i> &nbsp;
                @Html.ActionLink("Thêm mới", "Create", "HoaDonNhap")
            </button>
        </td>
    </tr>
</table>

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Mã hoá đơn</th>
            <th>Nhà cung cấp</th>
            <th>Tổng tiền (VNĐ)</th>
            <th>Ngày tạo</th>
            <th>Chức năng</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(item.MaSo.ToString("D6"))
                </td>
                <td>
                    @Html.Raw(commonDao.getRf_TenNhaCungCap(item.IDNhaCungCap))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TongTien)
                </td>
                <td>
                    @Html.Raw(@Convert.ToDateTime(item.CreatedDate).ToString("dd/MM/yyyy"))
                </td>
                <td>
                    <i class="fa fa-info-circle"></i> &nbsp;
                    @Html.ActionLink("Xem", "Details", new { id = item.IDHoaDonNhap }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-edit"></i> &nbsp;
                    @Html.ActionLink("Sửa", "Edit", new { id = item.IDHoaDonNhap }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-trash"></i> &nbsp;
                    @Html.ActionLink("Xóa", "Delete", new { id = item.IDHoaDonNhap }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
                </td>
            </tr>
        }
    </tbody>
</table>
@using (Html.BeginForm("Index", "HoaDonNhap", FormMethod.Get, new { id = "form1" }))
{
    <div class="pager">
        <table style="width:100%">
            <col style="width:50%">
            <col style="width:50%">
            <tr>
                <td style="float:left">
                    <b style="color:navy">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount &nbsp;&nbsp;-&nbsp;&nbsp;
                        @if (Model.Count == ViewBag.psize)
                        {
                            <span>Đang hiển thị (@(((Model.PageNumber * Model.Count) - Model.Count) + 1)-@(Model.PageNumber * Model.Count)) / @ViewBag.Count</span>
                        }
                        else
                        {
                            <span>Đang hiển thị (@((ViewBag.Count - Model.Count) + 1)-@(ViewBag.Count)) / @ViewBag.Count</span>
                        }
                    </b>
                </td>
                <td style="float:right; margin-top:-20px">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = ViewBag.psize, @searching = @ViewBag.SearchString }))
                </td>
            </tr>
        </table>
    </div>
}
<script src="~/Assets/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $("#checkAll").click(function () {
            if (this.checked) {
                $(".chkbox").prop('checked', $(this).prop('checked', true));
            }
            else {
                $('.chkbox').each(function () { this.checked = false; });
            }
        });
        $('.chkbox').on('click', function () {
            if ($('.chkbox:checked').length == $('.chkbox').length) {
                $('#checkAll').prop('checked', true);
            } else {
                $('#checkAll').prop('checked', false);
            }
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $("#pageSize").change(function () {
            $("#form1").submit();
        });
    });
</script>

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/HoaDonNhap/IndexChiTietHoaDonNhap.cshtml
@model IEnumerable<FreshFoodMongo.Models.DTO.ChiTietHoaDonNhap>
@{ 
    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
}

<button type="button" class="btn btn-success btn-admin" style="margin:5px; margin-left:unset; float:right">
    <i class="fa fa-plus-square"></i> &nbsp;
    @Html.ActionLink("Thêm chi tiết hóa đơn", "Create", "ChiTietHoaDonNhap", new { idhdn = ViewBag.IDHoaDonNhap, idncc = ViewBag.IDNhaCungCap }, new { @class = "" })
</button>


<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Sản phẩm
            </th>
            <th>
                Đơn vị tính
            </th>
            <th>
                Đơn giá (VNĐ)
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Thành tiền (VNĐ)
            </th>
            <th>Chức năng</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(commonDao.getRf_TenSanPham(item.IDSanPham))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonViTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonGiaNhap)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThanhTien)
                </td>
                <td>
                    @*<i class="fa fa-info-circle"></i> &nbsp;
                        @Html.ActionLink("Xem", "Details", "ChiTietHoaDonNhaps", new { id = item.IDChiTietHoaDonNhap , idhdn = ViewBag.IDHoaDonNhap }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*@
                    <i class="fa fa-edit"></i> &nbsp;
                    @Html.ActionLink("Sửa", "Edit", "ChiTietHoaDonNhap", new { id = item.IDChiTietHoaDonNhap, idhdn = ViewBag.IDHoaDonNhap }, new { @class = "" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-trash"></i> &nbsp;
                    @Html.ActionLink("Xóa", "Delete", "ChiTietHoaDonNhap", new { id = item.IDChiTietHoaDonNhap }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
                </td>
            </tr>
        }
    </tbody>
</table>