BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Models/DTO/DonHang.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FreshFoodMongo.Models.DTO
{
    public class DonHang
    {
        [BsonId]
        public ObjectId _id { get; set; }
        [BsonElement]
        public Guid IDDonHang { get; set; }
        [BsonElement]
        public Guid IDKhachHang { get; set; }
        [BsonElement]
        public int MaSo { get; set; }
        [BsonElement]
        public string TenNhanHang { get; set; }
        [BsonElement]
        public string SdtNhanHang { get; set; }
        [BsonElement]
        public string DiaChiNhanHang { get; set; }
        [BsonElement]
        public string GhiChu { get; set; }
        [BsonElement]
        public decimal? TienHang { get; set; }
        [BsonElement]
        public decimal? TienShip { get; set; }
        [BsonElement]
        public decimal? TienGiam { get; set; }
        [BsonElement]
        public decimal? TongTien { get; set; }
        [BsonElement]
        public Guid IDTrangThai { get; set; }
        [BsonElement]
        public Guid IDPhuongThucThanhToan { get; set; }
        [BsonElement]
        public DateTime? CreatedDate { get; set; }
        [BsonElement]
        public string CreatedBy { get; set; }
        [BsonElement]
        public DateTime? ModifiedDate { get; set; }
        [BsonElement]
        public string ModifiedBy { get; set; }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FreshFoodMongo.Models.DAO;
using FreshFoodMongo.Models.DAO.Admin;
using FreshFoodMongo.Models.DTO;
using MongoDB.Driver;

namespace FreshFoodMongo.Areas.Admin.Controllers
{
    public class DonHangsController : BaseController
    {
        DonHangDAO dhDao = new DonHangDAO();
        ChiTietDonHangDAO ctdhDao = new ChiTietDonHangDAO();
        BaseDAO baseDao = new BaseDAO();


        // GET: Admin/DonHangs
        public ActionResult Index(int? page, int? PageSize, string searching = "")
        {
            ViewBag.SearchString = searching;
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="10", Text= "10" },
                new SelectListItem() { Value="15", Text= "15" },
                new SelectListItem() { Value="20", Text= "20" },
                new SelectListItem() { Value="25", Text= "25" },
                new SelectListItem() { Value="50", Text= "50" }
            };
            int pageNumber = (page ?? 1);
            int pagesize = (PageSize ?? 10);
            ViewBag.psize = pagesize;
            ViewBag.Count = dhDao.ListSimple(searching).Count();
            return View(dhDao.ListSimpleSearch(pageNumber, pagesize, searching));
        }

        // GET: Admin/DonHangs/Details/5
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = dhDao.GetByID(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // GET: Admin/DonHangs/Create
        public ActionResult Create()
        {
            ViewBag.IDKhachHang = new SelectList(baseDao.getDataNguoiDung(), "IDNguoiDung", "Ten");
            ViewBag.IDPhuongThucThanhToan = new SelectList(baseDao.getDataPhuongThucThanhToan(), "IDPhuongThucThanhToan", "TenPhuongThucThanhToan");
            ViewBag.IDTrangThai = new SelectList(baseDao.getDataTrangThai(), "IDTrangThai", "TenTrangThai");
            return View();
        }

        // POST: Admin/DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //,CreatedBy,ModifiedDate,ModifiedBy
        public ActionResult Create([Bind(Include = "IDDonHang,IDKhachHang,GhiChu,TienHang,TienShip,TienGiam,TongTien,IDTrangThai,IDPhuongThucThanhToan,CreatedDate")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                donHang.IDDonHang = Guid.NewGuid();
                donHang.CreatedDate = DateTime.Now;
                donHang.CreatedBy = (string)Session["USERNAME_SESSION"];
                donHang.ModifiedDate = DateTime.Now;
                donHang.ModifiedBy = (string)Session["USERNAME_SESSION"];
                donHang.TongTien = 0;
                dhDao.Add(donHang);
                return RedirectToAction("Index");
            }

            ViewBag.IDKhachHang = new SelectList(baseDao.getDataNguoiDung(), "IDNguoiDung", "Ten", donHang.IDKhachHang);
            ViewBag.IDPhuongThucThanhToan = new SelectList(baseDao.getDataPhuongThucThanhToan(), "IDPhuongThucThanhToan", "TenPhuongThucThanhToan", donHang.IDPhuongThucThanhToan);
            ViewBag.IDTrangThai = new SelectList(baseDao.getDataTrangThai(), "IDTrangThai", "TenTrangThai", donHang.IDTrangThai);
            return View(donHang);
        }

        // GET: Admin/DonHangs/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = dhDao.GetByID(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDKhachHang = new SelectList(baseDao.getDataNguoiDung(), "IDNguoiDung", "Ten", donHang.IDKhachHang);
            ViewBag.IDPhuongThucThanhToan = new SelectList(baseDao.getDataPhuongThucThanhToan(), "IDPhuongThucThanhToan", "TenPhuongThucThanhToan", donHang.IDPhuongThucThanhToan);
            ViewBag.IDTrangThai = new SelectList(baseDao.getDataTrangThai(), "IDTrangThai", "TenTrangThai", donHang.IDTrangThai);
            return View(donHang);
        }

        // POST: Admin/DonHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDDonHang,IDKhachHang,GhiChu,TienHang,TienShip,TienGiam,TongTien,IDTrangThai,IDPhuongThucThanhToan,CreatedDate")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                donHang.ModifiedDate = DateTime.Now;
                donHang.ModifiedBy = (string)Session["USERNAME_SESSION"];
                dhDao.Edit(donHang);
                return RedirectToAction("Index");
            }
            ViewBag.IDKhachHang = new SelectList(baseDao.getDataNguoiDung(), "IDNguoiDung", "Ten", donHang.IDKhachHang);
            ViewBag.IDPhuongThucThanhToan = new SelectList(baseDao.getDataPhuongThucThanhToan(), "IDPhuongThucThanhToan", "TenPhuongThucThanhToan", donHang.IDPhuongThucThanhToan);
            ViewBag.IDTrangThai = new SelectList(baseDao.getDataTrangThai(), "IDTrangThai", "TenTrangThai", donHang.IDTrangThai);
            return View(donHang);
        }

        // GET: Admin/DonHangs/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dhDao.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult IndexChiTietDonHang(Guid id)
        {
            var listChiTietDonHang = ctdhDao.GetListChiTietDonHang(id);

            if (listChiTietDonHang == null)
                return HttpNotFound();

            ViewBag.IDDonHang = id;

            return PartialView(listChiTietDonHang);
        }


        public ActionResult Accept(Guid id)
        {
            var donHang = baseDao.getDataDonHang().FirstOrDefault(x => x.IDDonHang == id);
            donHang.IDTrangThai = new Guid("3240c2e6-fc6c-4feb-9313-382bd05cf522");
            donHang.ModifiedDate = DateTime.Now;
            donHang.ModifiedBy = (string)Session["USERNAME_SESSION"];
            dhDao.Edit(donHang);
            return RedirectToAction("Index");
        }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/DonHangs/Create.cshtml
@model FreshFoodMongo.Models.DTO.DonHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Đơn hàng - Thêm đơn hàng
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDKhachHang, "Tên khách hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDKhachHang", (IEnumerable<SelectListItem>)ViewBag.IDKhachHang, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaSo, "Mã đơn hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TienHang, "Tiền hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TienHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TienHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TienShip, "phí vận chuyển", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TienShip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TienShip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TienGiam, "Tiền giảm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TienGiam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TienGiam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TongTien, "Tổng tiền", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDTrangThai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTrangThai", (IEnumerable<SelectListItem>)ViewBag.IDTrangThai, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDPhuongThucThanhToan, "Phương thức thanh toán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDPhuongThucThanhToan", (IEnumerable<SelectListItem>)ViewBag.IDPhuongThucThanhToan, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDPhuongThucThanhToan, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, "Ngày tạo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, "Ngày cật nhật", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>*@



        @*<div class="form-group">
                @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary" value="Create" style="width:110px">
                    <i class="fa fa-save"></i> &nbsp;Lưu lại
                </button>
            </div>
        </div>
    </div>
}
<button type="button" class="btn btn-warning" style="width:110px">
    <i class="fa fa-th-list"></i> &nbsp;
    @Html.ActionLink("Danh sách", "Index")
</button>

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/DonHangs/Delete.cshtml
@model FreshFoodMongo.Models.DTO.DonHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DonHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NguoiDung.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhuongThucThanhToan.TenPhuongThucThanhToan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhuongThucThanhToan.TenPhuongThucThanhToan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai.TenTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai.TenTrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TienHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TienHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TienShip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TienShip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TienGiam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TienGiam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TongTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/DonHangs/Index.cshtml
@model PagedList.IPagedList<FreshFoodMongo.Models.DTO.DonHang>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int i;
    if (Model.Count == ViewBag.psize)
    {
        i = Model.PageNumber * Model.Count - Model.Count;
    }
    else
    {
        i = ViewBag.Count - Model.Count;
    }

    string GetSTT()
    {
        i++;
        return Convert.ToString(i);
    }

    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
}

@section header
{
    Danh sách đơn hàng
}

<table style="width:100%; margin-bottom:10px">
    <tr>
        <td>
            @using (Html.BeginForm("Index", "DonHangs", FormMethod.Get, new { id = "form1" }))
            {
                <p style="float:left; color:navy; height:32px"><b>Hiển thị &nbsp; </b>@Html.DropDownList("pageSize") &nbsp; <b>bản ghi / trang </b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

                <input type="text" name="searching" value="@ViewBag.SearchString" placeholder="Nhập thông tin tìm kiếm ..." style="width: 400px;" />
                <input type="submit" value="Tìm kiếm" />
            }
        </td>
        <td>
            @*<button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                    <i class="fa fa-plus-square"></i> &nbsp;
                    @Html.ActionLink("Thêm mới", "Create", "DonHangs")
                </button>*@
            @*<button type="button" class="btn btn-warning btn-admin" style="margin-bottom:10px; float: right; width:110px">
                    <i class="fa fa-filter"></i> &nbsp;
                    @Html.ActionLink("Bộ lọc", "Filter", "DonHangs")
                </button>*@
        </td>
    </tr>
</table>
<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Mã đơn hàng</th>
            <th>Tên khách hàng</th>
            <th>Phương thức thanh toán</th>
            <th>Trạng thái</th>
            <th>Tiền hàng</th>
            <th>Tiền ship</th>
            <th>Tiền giảm</th>
            <th>Tổng tiền</th>
            <th>Ngày tạo</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(item.MaSo.ToString("D6"))
                </td>
                <td>
                    @Html.Raw(commonDao.getRf_TenNguoiDung(item.IDKhachHang))
                </td>
                <td>
                    @Html.Raw(commonDao.getRf_TenPhuongThucThanhToan(item.IDPhuongThucThanhToan))
                </td>
                <td>
                    @Html.Raw(commonDao.getRf_TenTrangThai(item.IDTrangThai))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TienHang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TienShip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TienGiam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TongTien)
                </td>
                <td>
                    @Html.Raw(Convert.ToDateTime(item.CreatedDate).ToString("dd/MM/yyyy"))
                </td>
                <td>
                    @if (commonDao.getRf_TenTrangThai(item.IDTrangThai) == "Chờ xác nhận")
                    {
                        <i class="fa fa-check-square-o"></i> @*&nbsp;*@
                        @Html.ActionLink("Xác nhận", "Accept", new { id = item.IDDonHang }, new { onclick = "return confirm('Xác nhận đơn hàng?');", @class = "btn_accept" })
                    }
                    <i style="margin-left:4px;" class="fa fa-info-circle"></i> &nbsp;
                    @Html.ActionLink("Xem", "Details", new { id = item.IDDonHang }) @*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*@
                    @*<i class="fa fa-trash"></i> &nbsp;
                        @Html.ActionLink("Xóa", "Delete", new { id = item.IDDonHang }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })*@
                </td>
            </tr>
        }
    </tbody>
</table>

@using (Html.BeginForm("Index", "DonHangs", FormMethod.Get, new { id = "form1" }))
{
    <div class="pager">
        <table style="width:100%">
            <col style="width:50%">
            <col style="width:50%">
            <tr>
                <td style="float:left">
                    <b style="color:navy">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount &nbsp;&nbsp;-&nbsp;&nbsp;
                        @if (Model.Count == ViewBag.psize)
                        {
                            <span>Đang hiển thị (@(((Model.PageNumber * Model.Count) - Model.Count) + 1)-@(Model.PageNumber * Model.Count)) / @ViewBag.Count</span>
                        }
                        else
                        {
                            <span>Đang hiển thị (@((ViewBag.Count - Model.Count) + 1)-@(ViewBag.Count)) / @ViewBag.Count</span>
                        }
                    </b>
                </td>
                <td style="float:right; margin-top:-20px">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = ViewBag.psize, @searching = @ViewBag.SearchString }))
                </td>
            </tr>
        </table>
    </div>
}
<script src="~/Assets/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $("#checkAll").click(function () {
            if (this.checked) {
                $(".chkbox").prop('checked', $(this).prop('checked', true));
            }
            else {
                $('.chkbox').each(function () { this.checked = false; });
            }
        });
        $('.chkbox').on('click', function () {
            if ($('.chkbox:checked').length == $('.chkbox').length) {
                $('#checkAll').prop('checked', true);
            } else {
                $('#checkAll').prop('checked', false);
            }
        });
    });

</script>
<script type="text/javascript">
    $(function () {
        $("#pageSize").change(function () {
            $("#form1").submit();
        });
    });
</script>

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/DonHangs/IndexChiTietDonHang.cshtml
@model IEnumerable<FreshFoodMongo.Models.DTO.ChiTietDonHang>
@{
    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
}

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Sản phẩm
            </th>
            <th>
                Đơn vị tính
            </th>
            <th>
                Đơn giá (VNĐ)
            </th>
            <th>
                Số lượng
            </th>
            <th>
                Thành tiền
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(commonDao.getRf_TenSanPham(item.IDSanPham))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonViTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonGiaBan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoLuong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThanhTien)
                </td>
            </tr>
        }
    </tbody>
</table>