BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Models/DTO/NhaCungCap.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FreshFoodMongo.Models.DTO
{
    public class NhaCungCap
    {
        [BsonId]
        public ObjectId _id { get; set; }
        [BsonElement]
        public Guid IDNhaCungCap { get; set; }
        [BsonElement]
        public string Ten { get; set; }
        [BsonElement]
        public string DiaChi { get; set; }
        [BsonElement]
        public string HinhAnh { get; set; }
        [BsonElement]
        public string DienThoai { get; set; }
        [BsonElement]
        public DateTime? CreatedDate { get; set; }
        [BsonElement]
        public string CreatedBy { get; set; }
        [BsonElement]
        public DateTime? ModifiedDate { get; set; }
        [BsonElement]
        public string ModifiedBy { get; set; }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Controllers/NhaCungCapController.cs
using FreshFoodMongo.Models.DAO.Admin;
using FreshFoodMongo.Models.DTO;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreshFoodMongo.Areas.Admin.Controllers
{
    public class NhaCungCapController : BaseController
    {
        NhaCungCapDAO nccDao = new NhaCungCapDAO();
        NhaCungCapSanPhamDAO nccspDao = new NhaCungCapSanPhamDAO();
        // GET: Admin/NhaCungCap
        public ActionResult Index(int? page, int? PageSize, string searching = "")
        {
            ViewBag.SearchString = searching;
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem() { Value="10", Text= "10" },
                new SelectListItem() { Value="15", Text= "15" },
                new SelectListItem() { Value="20", Text= "20" },
                new SelectListItem() { Value="25", Text= "25" },
                new SelectListItem() { Value="50", Text= "50" }
            };
            int pageNumber = (page ?? 1);
            int pagesize = (PageSize ?? 10);
            ViewBag.psize = pagesize;
            ViewBag.Count = nccDao.ListSimple(searching).Count();
            return View(nccDao.ListSimpleSearch(pageNumber, pagesize, searching));
        }
        public ActionResult Details(Guid id)
        {
            NhaCungCap nhacungcap = nccDao.GetByID(id);
            return View(nhacungcap);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(string ten, string diachi, HttpPostedFileBase hinhanh,string dienthoai)
        {
            NhaCungCap nhacungcap = new NhaCungCap();
            nhacungcap.IDNhaCungCap = Guid.NewGuid();
            
            nhacungcap.Ten = ten;
            nhacungcap.DiaChi = diachi;
            nhacungcap.DienThoai = dienthoai;
            nhacungcap.CreatedDate = DateTime.Now;

            nhacungcap.CreatedDate = DateTime.Now;
            nhacungcap.CreatedBy = (string)Session["USERNAME_SESSION"];
            nhacungcap.ModifiedDate = DateTime.Now;
            nhacungcap.ModifiedBy = (string)Session["USERNAME_SESSION"];

            if (ModelState.IsValid)
            {
                if (hinhanh != null && hinhanh.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/Photos/"), System.IO.Path.GetFileName(hinhanh.FileName));
                    hinhanh.SaveAs(path);
                    nhacungcap.HinhAnh = hinhanh.FileName;
                }
                nccDao.Add(nhacungcap);
                return RedirectToAction("Index");
            }
            else
            {
                return View(nhacungcap);
            }
        }
        public ActionResult Edit(Guid id)
        {
            return View(nccDao.GetByID(id));
        }

        [HttpPost]
        public ActionResult Edit(Guid id,string ten, string diachi, HttpPostedFileBase hinhanh, string dienthoai)
        {
            NhaCungCap nhacungcap = nccDao.GetByID(id);
            nhacungcap.Ten = ten;
            nhacungcap.DiaChi = diachi;
            nhacungcap.DienThoai = dienthoai;

            nhacungcap.ModifiedDate = DateTime.Now;
            nhacungcap.ModifiedBy = (string)Session["USERNAME_SESSION"];

            if (ModelState.IsValid)
            {
                if (hinhanh != null && hinhanh.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Areas/Admin/Content/Photos/"), System.IO.Path.GetFileName(hinhanh.FileName));
                    hinhanh.SaveAs(path);
                    nhacungcap.HinhAnh = hinhanh.FileName;
                }
                nccDao.Edit(nhacungcap);
                return RedirectToAction("Index");
            }
            else
            {
                return View(nhacungcap);
            }
        }

        public ActionResult Delete(Guid id)
        {
            nccDao.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult IndexNhaCungCapSanPham(Guid id)
        {
            var listSanPhamCungCap = nccspDao.GetListSPCungUngByIDNhaCungCap(id);

            if (listSanPhamCungCap == null)
                return HttpNotFound();

            ViewBag.IDNhaCungCap = id;

            return PartialView(listSanPhamCungCap);
        }
    }
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/NhaCungCap/Create.cshtml
@model FreshFoodMongo.Models.DTO.NhaCungCap

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Nhà cung cấp  - Thêm nhà cung cấp
}



@using (Html.BeginForm("Create", "NhaCungCap", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Tên nhà cung cấp</label>
                <input type="text" class="form-control" name="ten" placeholder="Nhập tên nhà cung cấp ..." value=" @Html.DisplayFor(model => model.Ten)" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Địa Chỉ</label><br />
                <input type="text" class="form-control" name="diachi" placeholder="Nhập địa chỉ ..." value=" @Html.DisplayFor(model => model.DiaChi)" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Số điện thoại</label><br />
                <input type="text" class="form-control" name="dienthoai" placeholder="Nhập đơn vị tính ..." value=" @Html.DisplayFor(model => model.DienThoai)" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputFile">Hình ảnh nhà cung cấp</label>
                <input type="file" id="hinhanh" name="hinhanh" required>
            </div>
        </div>
        <br />

        <button type="submit" class="btn btn-primary" style="width:110px">
            <i class="fa fa-save"></i> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning" style="width:110px">
            <i class="fa fa-th-list"></i> &nbsp;
            @Html.ActionLink("Danh sách", "Index")
        </button>
    </div>
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/NhaCungCap/Details.cshtml
@model FreshFoodMongo.Models.DTO.NhaCungCap

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Nhà cung cấp - Thông tin nhà cung cấp (@Model.Ten)
}

<div>
    <table style="width:60%">
        <td style="vertical-align:top">
            <div class="form-group">
                <div class="col-md-10">
                    <img height="200" width="200" src="~/Areas/Admin/Content/Photos/@Model.HinhAnh" alt="Chưa có" style="border:solid 1px gray; border-radius:10px" />
                </div>
            </div>
        </td>
        <td style="vertical-align:top">
            <dl class="dl-horizontal">
                <dt>
                    Tên Nhà Cung cấp:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Ten)
                </dd>

                <dt>
                    Địa Chỉ:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DiaChi)
                </dd>


                <dt>
                    Điện Thoại:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DienThoai)
                </dd>
            </dl>
        </td>
    </table>
    <br />
    <button type="button" class="btn btn-primary">
        <a class="fa fa-edit"></a> &nbsp;
        @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.IDNhaCungCap })
    </button>
    <button type="button" class="btn btn-warning" style="width:110px">
        <a class="fa fa-arrow-left"></a> &nbsp;
        @Html.ActionLink("Trở về", "Index")
    </button>
    <br /><br />
    <hr />
    <h4>
        <i class="fa fa-list-ol"></i>
        <b style="color:darkgreen">&nbsp;Danh sách Sản phẩm cung ứng</b>
    </h4>
    @Html.Action("IndexNhaCungCapSanPham", new { id = Model.IDNhaCungCap })
</div>
<br />

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/NhaCungCap/Edit.cshtml
@model FreshFoodMongo.Models.DTO.NhaCungCap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section header
{
    Nhà cung cấp - Chỉnh sửa thông tin (@Model.Ten )
}

@using (Html.BeginForm("Edit", "NhaCungCap", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDNhaCungCap)


        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Tên nhà cung cấp</label>
                <input type="text" class="form-control" name="ten" placeholder="Nhập tên nhà cung cấp ..." value=" @Html.DisplayFor(model => model.Ten)" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Địa Chỉ</label><br />
                <input type="text" class="form-control" name="diachi" placeholder="Nhập địa chỉ ..." value=" @Html.DisplayFor(model => model.DiaChi)" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Số điện thoại</label><br />
                <input type="text" class="form-control" name="dienthoai" placeholder="Nhập đơn vị tính ..." value=" @Html.DisplayFor(model => model.DienThoai)" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <label for="exampleInputFile">Hình ảnh nhà cung cấp</label>
                <input type="file" id="hinhanh" name="hinhanh">
            </div>
        </div>
        <br />


        <button type="submit" class="btn btn-primary btn-admin" style="width:110px">
            <a class="fa fa-save"></a> &nbsp;Lưu lại
        </button>
        <button type="button" class="btn btn-warning btn-admin" style="width:110px">
            <a class="fa fa-th-list"></a> &nbsp;
            @Html.ActionLink("Danh sách", "Index")
        </button>
    </div>
}

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/NhaCungCap/Index.cshtml
@model PagedList.IPagedList<FreshFoodMongo.Models.DTO.NhaCungCap>
@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int i;
    if (Model.Count == ViewBag.psize)
    {
        i = Model.PageNumber * Model.Count - Model.Count;
    }
    else
    {
        i = ViewBag.Count - Model.Count;
    }

    string GetSTT()
    {
        i++;
        return Convert.ToString(i);
    }
}

@section header
{
    Danh sách Nhà cung cấp
}

<table style="width:100%; margin-bottom:10px">
    <tr>
        <td>
            @using (Html.BeginForm("Index", "NhaCungCap", FormMethod.Get, new { id = "form1" }))
            {
                <p style="float:left; color:navy; height:32px"><b>Hiển thị &nbsp; </b>@Html.DropDownList("pageSize") &nbsp; <b>bản ghi / trang </b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>

                <input type="text" name="searching" value="@ViewBag.SearchString" placeholder="Nhập thông tin tìm kiếm ..." style="width: 400px;" />
                <input type="submit" value="Tìm kiếm" />
            }
        </td>
        <td>
            <button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                <i class="fa fa-plus-square"></i> &nbsp;
                @Html.ActionLink("Thêm mới", "Create", "NhaCungCap")
            </button>
        </td>
    </tr>
</table>

<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>STT</th>
            <th>Tên nhà cung cấp</th>
            <th>Địa Chỉ</th>
            <th>Hình ảnh</th>
            <th>Điện Thoại</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(GetSTT())
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    <img height="20" width="30" src="~/Areas/Admin/Content/Photos/@item.HinhAnh" alt="Chưa có" style="border: solid 1px #80808038" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DienThoai)
                </td>
                <td>
                    <i class="fa fa-info-circle"></i> &nbsp;
                    @Html.ActionLink("Xem", "Details", new { id = item.IDNhaCungCap }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-edit"></i> &nbsp;
                    @Html.ActionLink("Sửa", "Edit", new { id = item.IDNhaCungCap }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-trash"></i> &nbsp;
                    @Html.ActionLink("Xóa", "Delete", new { id = item.IDNhaCungCap }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
                </td>

            </tr>
        }
    </tbody>
</table>


@using (Html.BeginForm("Index", "NhaCungCap", FormMethod.Get, new { id = "form1" }))
{
    <div class="pager">
        <table style="width:100%">
            <col style="width:50%">
            <col style="width:50%">
            <tr>
                <td style="float:left">
                    <b style="color:navy">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount &nbsp;&nbsp;-&nbsp;&nbsp;
                        @if (Model.Count == ViewBag.psize)
                        {
                            <span>Đang hiển thị (@(((Model.PageNumber * Model.Count) - Model.Count) + 1)-@(Model.PageNumber * Model.Count)) / @ViewBag.Count</span>
                        }
                        else
                        {
                            <span>Đang hiển thị (@((ViewBag.Count - Model.Count) + 1)-@(ViewBag.Count)) / @ViewBag.Count</span>
                        }
                    </b>
                </td>
                <td style="float:right; margin-top:-20px">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = ViewBag.psize, @searching = @ViewBag.SearchString }))
                </td>
            </tr>
        </table>
    </div>
}
<script src="~/Assets/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $("#checkAll").click(function () {
            if (this.checked) {
                $(".chkbox").prop('checked', $(this).prop('checked', true));
            }
            else {
                $('.chkbox').each(function () { this.checked = false; });
            }
        });
        $('.chkbox').on('click', function () {
            if ($('.chkbox:checked').length == $('.chkbox').length) {
                $('#checkAll').prop('checked', true);
            } else {
                $('#checkAll').prop('checked', false);
            }
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $("#pageSize").change(function () {
            $("#form1").submit();
        });
    });
</script>

BigData-FreshFoodMongo/FreshFoodMongo/FreshFoodMongo/Areas/Admin/Views/NhaCungCap/IndexNhaCungCapSanPham.cshtml
@model IEnumerable<FreshFoodMongo.Models.DTO.NhaCungCapSanPham>
@{
    FreshFoodMongo.Models.DAO.CommonDAO commonDao = new FreshFoodMongo.Models.DAO.CommonDAO();
 }

<button type="button" class="btn btn-success btn-admin" style="margin:5px; margin-left:unset; float:right">
    <i class="fa fa-plus-square"></i> &nbsp;
    @Html.ActionLink("Thêm sản phẩm cung ứng", "Create", "NhaCungCapSanPham", new { idncc = ViewBag.IDNhaCungCap }, new { @class = "" })
</button>


<table id="example1" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Sản phẩm
            </th>
            <th>
                Đơn vị tính
            </th>
            <th>
                Giá cung ứng (VNĐ)
            </th>
            <th>
                Ngày cập nhật
            </th>
            <th>
                Chức năng
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(commonDao.getRf_TenSanPham(item.IDSanPham))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonViTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GiaCungUng)
                </td>
                <td>
                    @Html.Raw(Convert.ToDateTime(item.NgayCapNhat).ToString("dd/MM/yyyy"))
                </td>
                <td>
                    @*<i class="fa fa-info-circle"></i> &nbsp;
                        @Html.ActionLink("Xem", "Details", "ChiTietHoaDonNhaps", new { id = item.IDChiTietHoaDonNhap , idhdn = ViewBag.IDHoaDonNhap }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*@
                    <i class="fa fa-edit"></i> &nbsp;
                    @Html.ActionLink("Sửa", "Edit", "NhaCungCapSanPham", new { id = item.IDNhaCungCapSanPham }, new { @class = "" }) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fa fa-trash"></i> &nbsp;
                    @Html.ActionLink("Xóa", "Delete", "NhaCungCapSanPham", new { id = item.IDNhaCungCapSanPham }, new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
                </td>
            </tr>
        }
    </tbody>
</table>